# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'Photo Map' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~> 3.0'
  # Pods for Photo Map

  target 'Photo MapTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
